name: build-and-push

on: push
  # push:
  #   branches:
  #     - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['debian-asdf-erlang-elixir-nodejs', 'debian-backup-postgresql-to-b2', 'ubuntu-asdf-erlang-elixir-nodejs'] }
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.dir }}"
          platforms: linux/amd64 #,linux/arm64 - disabled for now, JIT support makes it crash during build :x
          push: true
          cache-from: type=registry,ref=vivakit/${{ matrix.dir }}:buildcache
          cache-to: type=registry,ref=vivakit/${{ matrix.dir }}:buildcache,mode=max
          tags: vivakit/${{ matrix.dir }}:${{ github.sha }}
